choropleth:
    figsize_x: 10
    figsize_y: 10
    dpi: 300
    crs: "EPSG:3857"

    linewidth: 0.5
    edgecolor: "gainsboro" 
    font_type: "Roboto"

    title: "{} in {}"
    title_fontsize: 15
    subtitle_fontsize: 10
    subtitle_gap: 0.005
    annotation_fontsize: 8
    annotation_gap: 0.01
    annotation_color: "#909090"
    
    legend_title_x: -5.05
    legend_title_y: 1.05
    legend_type: 'default'
    
    legend_shrink: 0.25
    legend_title_gap: 1.025
    legend_title_fontsize: 7
    legend_label_fontsize: 7

    barplot_x_offset: 0
    barplot_y_offset: -0.2
    barplot_nbins: 10
    barplot_width: 0.2
    barplot_height: 0.3
    barplot_tick_size: 7
    barplot_label_color: "dimgray"
    barplot_label_size: 5
    
    missing_color: "silver"
    missing_edgecolor: "gainsboro"
    missing_linewidth: 0.3
    missing_hatch: "/////"
    missing_label: "No data"
    missing_legend_fontsize: "small"
    missing_legend_loc: "lower right"
    missing_hatch_linewidth: 0.2
    
    cmap: "ylgnbu"
    fontsize: 5
    label_facecolor: 'white'
    label_edgecolor: 'gainsboro'
    label_linewidth: 0.3
    label_alpha: 0.7
    label_boxstyle: 'round,pad=0.5'


bivariate_choropleth:
    figsize_x: 10
    figsize_y: 10
    dpi: 300
    crs: "EPSG:3857"

    linewidth: 0.2
    edgecolor: "white"
    font_type: "Roboto"

    title: "{} and {} in {}"
    title_fontsize: 15
    subtitle_fontsize: 10
    subtitle_gap: 0.005
    annotation_fontsize: 8
    annotation_gap: 0.01
    annotation_color: "#909090"
    legend_fontsize: 5
    
    missing_color: "silver"
    missing_edgecolor: "gainsboro"
    missing_linewidth: 0.3
    missing_hatch: "/////"
    missing_label: "No data"
    missing_legend_fontsize: "small"
    missing_legend_loc: "lower right"
    missing_hatch_linewidth: 0.2

    fontsize: 5
    label_facecolor: 'white'
    label_edgecolor: 'gainsboro'
    label_linewidth: 0.3
    label_alpha: 0.7
    label_boxstyle: 'round,pad=0.5'

    cmap4: [
        '#d3d3d3', '#b0c1c7', '#8bafbb', '#689cad', 
        '#c6aaaa', '#a49ba0', '#818d97', '#5d7e8b', 
        '#b87f7f', '#977479', '#76686f', '#555d69',
        '#ad5253', '#8d4b4d', '#6d4447', '#4c3d43'
    ]

    cmap5: [
        "#afafaf", "#a1abaf", "#92a7af", "#84a4b0", "#75a0b1", 
        "#a79595", "#9a9296", "#8c8f96", "#7e8c96", "#708897", 
        "#9f7a7b", "#92787c", "#85757c", "#78737c", "#6a707d", 
        "#976061", "#8b5e61", "#7f5c61", "#725a62", "#655862", 
        "#8f4445", "#844345", "#784145", "#6c4045", "#603e46"
    ]

    cmap5_aqua: [
        "#d3d3d3", "#b1d1d1", "#88cfcf", "#56cbcb", "#00c5c5", 
        "#ceabc7", "#acaac6", "#85a7c3", "#53a4c0", "#00a0ba", 
        "#c881bb", "#a780b9", "#817eb6", "#517cb3", "#0079ae", 
        "#c252ac", "#a251aa", "#7d50a8", "#4f4fa5", "#004da1", 
        "#b70092", "#990091", "#76008f", "#4a008d", "#000089"
    ]


geoboundaries:
    figsize_x: 10
    figsize_y: 10
    dpi: 300
    crs: "EPSG:3857"

    title: "{} Administrative Units"
    legend_title: "Regional Groupings"
    
    title_fontsize: 15
    subtitle_fontsize: 10
    subtitle_gap: 0.005
    annotation_fontsize: 7
    annotation_gap: 0.01
    annotation_color: "#909090"

    edgecolor_with_group: "white"
    edgecolor_no_group: "gainsboro"
    linewidth_with_group: 0.2
    linewidth_no_group: 0.4

    fontsize: 5
    label_facecolor: 'white'
    label_edgecolor: 'gainsboro'
    label_linewidth: 0.3
    label_alpha: 0.7
    label_boxstyle: 'round,pad=0.5'

    group_linewidth: 0.2
    group_edgecolor: "white"
    group_legend_loc: 'best'
    group_legend_title_fontsize: 'small'
    group_legend_fontsize: 'x-small'
    group_legend_box_align: 'left'
    group_legend_x: -0.3
    group_legend_y: 0.7
    group_legend_width: 0.2
    group_legend_height: 0.2
    cmap: "tableau_20"
    

raster:
    figsize_x: 10
    figsize_y: 10
    dpi: 300

    title_fontsize: 13
    subtitle_fontsize: 10
    subtitle_gap: 0.005
    annotation_fontsize: 7
    annotation_gap: 0.01
    annotation_color: "#909090"

    legend_title_x: 1.0
    legend_title_y: 1.025
    legend_title_loc: "center"
    legend_title_fontsize: 7
    legend_label_fontsize: 7
    
    title: "{} in {}"
    cmap: "haline_r"

    cbar_width: "3%"
    cbar_height: "50%"
    cbar_loc: 'center left'
    cbar_bbox_x: -0.35
    cbar_bbox_y: 0
    cbar_bbox_width: 1
    cbar_bbox_height: 1
    cbar_pad: 0.04
    cbar_fontsize: 7

hatches:
    crs: "EPSG:3857"
    hatches: ["//////", "++++++", "||||||", "------", r"\\\\\\"]
    legend_title_fontsize: 7
    legend_label_fontsize: 7
    linewidth: 0.5

lines:
    figsize_x: 10
    figsize_y: 10
    dpi: 300
    crs: "EPSG:3857"

    legend_title_fontsize: 7
    legend_label_fontsize: 7
    edgecolor: "gainsboro"
    linewidth: 0.7
    alpha: 0.9

    markerscale: 10
    labelspacing: 1.5
    cmap: "set2"
    tolerance: 100

points:
    figsize_x: 10
    figsize_y: 10
    dpi: 300
    crs: "EPSG:3857"

    legend_title_fontsize: 7
    legend_label_fontsize: 7
    edgecolor: "gainsboro"
    linewidth: 0.2
    alpha: 0.7

    markerscale: 3
    marker: 'o'
    labelspacing: 1.5
    cmap: "bold"

    fontsize: 5
    label_facecolor: 'white'
    label_edgecolor: 'gainsboro'
    label_linewidth: 0.3
    label_alpha: 0.3
    label_boxstyle: 'round,pad=0.5'

folium:
    tiles: 'cartodbpositron'
    zoom_start: 6
    fill_opacity: 0.9
    fill_color: "YlGnBu"
    line_color: "lightgrey"
    meter_crs: "EPSG:3857"
    
    style_function:
        fillColor: '#ffffff' 
        color: '#000000' 
        fillOpacity: 0.1 
        weight: 0.1
        lineColor: '#ffffff'
    
    highlight_function:
        fillColor: '#000000'
        color: '#000000' 
        fillOpacity: 0.50, 
        weight: 0.1

assets_alias:
    worldcover_builtup: "Built-up Area"
    worldcover_cropland: "Cropland Area"
    bem: "Building Valuation"
    worldpop: "Population"
    landscan: "Population"

hazards_alias:
    coastal_defended_fathom: "Coastal Flood"
    fluvial_defended_fathom: "Fluvial Flood"
    pluvial_defended_fathom: "Pluvial Flood"
    landslide_earthquake_gfdrr: "Earthquake-triggered Landslide"
    landslide_precip_gfdrr: "Precipitation-triggered Landslide"
    fluvial_flood_cdri: "Fluvial Flood"
    wildfire_geos5: "Wildfires"
    heat_stress: "Heat Stress"
    earthquake: "Earthquakes"
    drought_spei: "Droughts"
    cyclone: "Cyclones"

legend_titles:
    tag: "Infrastructure"
    disorder_type: "ACLED Conflict Disorder Type"
    event_type: "ACLED Conflict Event Type"
    sub_event_type: "ACLED Conflict Sub-event Type"
    disaster_idp_total: "Number of IDPs \nfrom Disasters"
    conflict_idp_total: "Number of IDPs \nfrom Conflicts"
    idp_total: "Total number of IDPs"
    idp_mean: "Average number of IDPs"
    osm_category: "OSM Category"
    total_conflict_count: "Number of conflict events"
    conflict_count: "Number of conflict events \naffecting {}"
    fatalities_per_conflict: "Number of fatalities per conflict"
    fatalities: "Number of fatalities"
    intensity_weighted_exposure_relative: "Intensity-weighted Relative \n{} Exposure Score"
    intensity_weighted_exposure: "Intensity-weighted \n{} Exposure Score"
    mhs: "{} \n{} Exposure Score"
    exposure_relative: "Proportion of {} \nexposed to {}"
    exposure: "{} exposed \nto {}"
    landslide_earthquake: "Mean Average Annual Frequency \nof Earthquake-triggered Landslide"
    landslide_precip: "Mean Average Annual Frequency \nof Precipitation-triggered Landslide"
    earthquake: "Peak Ground \nAcceleration (PGA)"
    cyclone: "Windspeed"
    worldcover_builtup: "Built-up Area"
    worldcover_cropland: "Crop Land Area"
    bem: "Building Valuation"
    worldpop: "Population"
    landscan: "Population"


var_titles:
    disaster_idp_total: "Number of IDPs from Disasters"
    conflict_idp_total: "Number of IDPs from Conflicts"
    idp_total: "Total number of IDPs"
    idp_mean: "Average number of IDPs"
    total_conflict_count: "Number of Conflict Events"
    total_fatalities_per_conflict: "Fatalities per Conflict"
    conflict_count: "Number of Conflict Events Affecting {}"
    fatalities_per_conflict: "Fatalities per Conflict Affecting {}"
    fatalities: "Number of Fatalities"
    intensity_weighted_exposure_relative: "Intensity-weighted Relative {} Exposure to {}"
    exposure_relative: "Relative {} Exposure to {}"
    exposure: "Absolute {} Exposure to {}"
    worldcover_builtup: "Built-up Area"
    worldcover_cropland: "Crop Land Area"
    bem: "Building Valuation"
    worldpop: "Population"
    landscan: "Population"

    
annotations:
    coastal_defended_fathom: "Coastal Flood Hazard Map (Fathom v3.0, 2020)"
    fluvial_defended_fathom: "Fluvial Flood Hazard Map (Fathom v3.0, 2020)"
    pluvial_defended_fathom: "Pluvial Flood Hazard Map (Fathom v3.0, 2020)"
    idmc: "IDP data from IDMC Global Internal Displacement Database (GIDD)"
    dtm: "IDP data from IOM Displacement Tracking Matrix (DTM)"
    worldcover: "ESA WorldCover 10 m 2021 v200 (Zanaga, et al., 2022)"
    bem: "The GIRI Global Building Exposure Model (BEM) (Pillar et al., 2023)"
    geoboundary: "Administrative boundaries from geoBoundaries (Runfola, D. et al., 2020)"
    gadm: "Administrative boundaries from GADM v4.1"
    mimu: "Administrative boundaries from Myanmar Information Management Unit (MIMU) v9.4"
    mhs: "Multihazard Score, The World Bank Group, 2025"
    cyclone: "Global Tropical Cyclone Wind RP 250 from Coalition for Disaster Resilient Infrastructure (CDRI)"
    landslide: "Global Landslide Hazard Map, The World Bank (2021)"
    earthquake: "Global Earthquake Model (GEM) Seismic Hazard Map (version 2023.1 - June 2023)"
    drought: "SPEI Drought Indices from Drought.gov and CSIC (Vicente-Serrano, et al., 2010)"
    fluvial_flood: "Global Flood Hazard Continuum model (Silvestro et al. 2013 and 2015)"
    heat_stress: "GloUTCI-M: A Global Monthly 1 km Universal Thermal Climate Index Dataset (2022) (Yang et al., 2023)"
    wildfire_geos5: "Global Fire Weather Database (GFWED) NASA GEOS-5 Fire Weather index (FWI) (Field et al., 2015)"
    wildfire_gwis: "Fire Weather Index (FWI) (Di Giuseppe, et al., 2023)"
    worldpop: "WorldPop (www.worldpop.org - University of Southampton, 2018)"
    acled: "Conflict data from Armed Conflict Location & Event Data Project (ACLED)"
    ucdp: "Conflict data from UCDP (Sundberg, Ralph, and Erik Melander, 2013)"
    landscan: "LandScan 2024 from Oak Ridge National Laboratory (Lebakula, et al., 2024)"

definition:
    